### PR TITLE
GPIO mappings in README match those in the .ini

### PR DESCRIPTION
**Pull request by christiansievers**
plus a few small clarifications in the README

(I think it makes things easier to understand and adjust settings if the example GPIO mappings in README match the example mappings in the .ini. At least that's what I thought when I tested the new GPIO features and sort of expected them to be the same...)

### CODE REVIEW

**Comment by christiansievers** [comment]
here are a few specially named small videos I quickly made to test the jumping back and forth functions - maybe useful for others, too [test_videos.zip](https://github.com/adafruit/pi_video_looper/files/14298593/test_videos.zip)

**Comment by tofuSCHNITZEL** [comment]
Thanks! should we include the test videos in the repo?

**Comment by christiansievers** [comment]
No, they're too strange :)  I was thinking, this might have to be a new repo just with test videos. Numbered like this, but also different file types, video containers, video codecs. Different aspect ratios. Also test images like they used to have on TV, those still exist and are still useful sometimes.

By the way, those GPIO controls work great.

**Comment by tofuSCHNITZEL** [comment]
okay yes and or you link/host it on your videolooper website...

**Pull request merged**
